import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'bn' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  n: (num: number | string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'bn',
  setLanguage: () => {},
  t: (key) => key,
  n: (num) => String(num),
});

const translations: Record<string, string> = {
  // Navigation / Header
  "Home": "হোম",
  "Detected Fraud Pages": "শনাক্তকৃত প্রতারক পেজ",
  "Blog": "ব্লগ",
  "Write a Review": "রিভিউ লিখুন",
  "Log In": "লগইন",
  "Log In/Sign Up": "লগইন/নিবন্ধন",
  "For businesses": "ব্যবসার জন্য",
  "Business Dashboard": "বিজনেস ড্যাশবোর্ড",
  "Admin Panel": "অ্যাডমিন প্যানেল",
  "Log Out": "লগ আউট",
  "Sign Up": "নিবন্ধন করুন",
  "My Reviews": "আমার রিভিউ",
  "My Settings": "আমার সেটিংস",
  "Help": "সাহায্য",
  "Menu": "মেনু",
  "Reviews": "রিভিউ",
  "Fraud Pages": "প্রতারক পেজ",
  "Business Log In": "বিজনেস লগইন",
  "Business Sign Up": "বিজনেস সাইনআপ",
  "Back to Public Website": "পাবলিক ওয়েবসাইটে ফিরে যান",
  "Your data is secure and never shared.": "আপনার তথ্য নিরাপদ এবং কখনই শেয়ার করা হয় না।",

  // Footer
  "Quick Links": "কুইক লিংক",
  "Claim Your Page": "আপনার পেজ দাবি করুন",
  "Company": "কোম্পানি",
  "About Us": "আমাদের সম্পর্কে",
  "Contact Us": "যোগাযোগ করুন",
  "Privacy Policy": "প্রাইভেসি পলিসি",
  "Terms & Conditions": "শর্তাবলী ও নিয়মাবলী",
  "Disclaimer": "দাবিত্যাগ",
  "Safety": "নিরাপত্তা",
  "Report a Fraud Page": "প্রতারক পেজ রিপোর্ট করুন",
  "Review Guidelines": "রিভিউ নির্দেশিকা",
  "How Reviews Work": "রিভিউ যেভাবে কাজ করে",
  "Dispute Policy": "বিরোধ নীতি",
  "Content Removal Policy": "কনটেন্ট অপসারণ নীতি",
  "Need Help?": "সহায়তা প্রয়োজন?",
  "We're here to help you shop with confidence.": "আমরা আছি আপনার অনলাইন কেনাকাটাকে নিরাপদ ও সহজ করতে।",
  "Email Us": "আমাদের ইমেইল করুন",
  "Follow Us": "আমাদের ফলো করুন",
  "For support, corrections, or business inquiries, contact us by email or Facebook.": "সহায়তা, সংশোধন বা ব্যবসায়িক অনুসন্ধানের জন্য ইমেইল বা ফেসবুকের মাধ্যমে আমাদের সাথে যোগাযোগ করুন।",
  "FB Page Review helps users check Facebook pages, seller profiles, reviews, fraud reports, and payment numbers before buying online.": "ফেসবুক পেজ রিভিউ ব্যবহারকারীদের অনলাইন কেনাকাটার পূর্বে ফেসবুক পেজ, বিক্রেতার প্রোফাইল, রিভিউ, প্রতারণার রিপোর্ট এবং পেমেন্ট নম্বর যাচাই করতে সাহায্য করে।",
  "Trusted by thousands of users to shop safely.": "সহস্রাধিক ব্যবহারকারীর কাছে বিশ্বস্ত, কেনাকাটা হোক নিরাপদ।",
  "Trusted by thousands of users to": "সহস্রাধিক ব্যবহারকারীর কাছে বিশ্বস্ত, কেনাকাটা হোক",
  "shop safely.": "নিরাপদ।",

  // Hero Section
  "SHOP SMART, STAY SAFE": "স্মার্ট কেনাকাটা করুন, নিরাপদ থাকুন",
  "Check Facebook Pages": "ফেসবুক পেজ চেক করুন",
  "Before You Pay": "পেমেন্ট করার আগে",
  "Search sellers, usernames, and bKash numbers to avoid fraud and shop with confidence.": "প্রতারণা এড়াতে এবং বিশ্বস্ততার সাথে কেনাকাটা করতে বিক্রেতা, ইউজারনেম এবং বিকাশ/নগদ নম্বর দিয়ে চেক করুন।",
  "Search page name, page URL, bKash / Nagad number...": "পেজের নাম, পেজ লিংক, বিকাশ / নগদ নম্বর দিয়ে খুঁজুন...",
  "Examples": "উদাহরণ",
  "Report a Fraud": "প্রতারণা রিপোর্ট করুন",

  // Statistics
  "Pages Scanned": "স্ক্যানকৃত পেজ",
  "Scam Numbers": "প্রতারক নম্বর",
  "New Scams Today": "আজকের নতুন প্রতারণা",
  "Total Pages Scanned": "মোট পেজ স্ক্যান",

  // Home sections
  "Recently Detected Fraud Pages": "সম্প্রতি শনাক্তকৃত প্রতারক পেজ",
  "Recent Reviews & Reports": "সাম্প্রতিক রিভিউ এবং রিপোর্ট",
  "Show all results": "সব ফলাফল দেখুন",
  "Popular Searches": "জনপ্রিয় অনুসন্ধান",
  "Show More": "আরও দেখুন",
  "Show Less": "কম দেখুন",
  "view all": "সব দেখুন",
  "View All": "সব দেখুন",
  "Search results for": "অনুসন্ধানের ফলাফল",
  "No exact matches found.": "কোনো সঠিক মিল পাওয়া যায়নি।",
  "Search for close matches or create a new page.": "অনুরূপ পেজ খুঁজুন অথবা একটি নতুন পেজ তৈরি করুন।",

  // Page Profile / Details
  "Verified Seller": "যাচাইকৃত বিক্রেতা",
  "Gold Seller": "গোল্ড বিক্রেতা",
  "Suspicious": "সন্দেহজনক",
  "Under Review": "পর্যালোচনার অধীনে",
  "Fraud": "প্রতারক",
  "Risk Reports": "ঝুঁকি রিপোর্ট",
  "reviews": "রিভিউ",
  "reports": "রিপোর্ট",
  "Average Rating": "গড় রেটিং",
  "Total Reviews": "মোট রিভিউ",
  "Total Reports": "মোট রিপোর্ট",
  "Page Details": "পেজের বিবরণ",
  "Trust Score": "বিশ্বাসযোগ্যতা স্কোর",
  "Contact Info": "যোগাযোগের তথ্য",
  "Reported Numbers": "রিপোর্টকৃত নম্বর",
  "Add Review": "রিভিউ যোগ করুন",
  "Read More": "আরও পড়ুন",
  "Read Less": "কম পড়ুন",
  "No reviews yet.": "এখনও কোনো রিভিউ নেই।",
  "Be the first to review!": "প্রথম রিভিউটি আপনিই লিখুন!",
  "Facebook Page Name": "ফেসবুক পেজের নাম",
  "Facebook Username": "ফেসবুক ইউজারনেম",
  "Page Link": "পেজ লিংক",
  "Whatsapp Number": "হোয়াটসঅ্যাপ নম্বর",
  "Website": "ওয়েবসাইট",
  "Page Created": "পেজ তৈরির সময়",
  "Page ID": "পেজ আইডি",
  "Followers": "ফলোয়ার",
  "Category": "ক্যাটাগরি",
  "Verified Page": "ভেরিফাইড পেজ",
  "Scam Report Details": "প্রতারণা রিপোর্টের বিবরণ",
  "Status": "স্ট্যাটাস",

  // Write Review
  "Write your review...": "আপনার রিভিউ লিখুন...",
  "Report as Fraud": "প্রতারক হিসেবে রিপোর্ট করুন",
  "Please log in to write a review.": "রিভিউ লিখতে দয়া করে লগইন করুন।",
  "Select Rating": "রেটিং নির্বাচন করুন",
  "Title": "শিরোনাম",
  "Description": "বর্ণনা",
  "Facebook Page URL": "ফেসবুক পেজ লিংক",
  "Seller Phone Number": "বিক্রেতার ফোন নম্বর",
  "bKash / Nagad Number": "বিকাশ / নগদ নম্বর",
  "Submit": "জমা দিন",
  "Cancel": "বাতিল করুন",
  "Submit Review": "রিভিউ জমা দিন",
  "Submit Report": "রিপোর্ট জমা দিন",

  // Blog
  "Latest Security News & Help Guides": "সর্বশেষ নিরাপত্তা সংবাদ এবং সহায়তা গাইড",
  "Read our security news, guides, and tips to help you stay safe while navigating Facebook marketplaces and online transactions in Bangladesh.": "বাংলাদেশে ফেসবুক মার্কেটপ্লেস এবং অনলাইন লেনদেনে নিরাপদ থাকতে আমাদের নিরাপত্তা সংবাদ, গাইড এবং পরামর্শগুলো পড়ুন।",
  "Search Blog...": "ব্লগ খুঁজুন...",
  "No blog posts found.": "কোনো ব্লগ পোস্ট পাওয়া যায়নি।",
  "Back to Blog": "ব্লগে ফিরে যান",
  "Published on": "প্রকাশের তারিখ",
  "By": "দ্বারা",
  "Comments": "মন্তব্য",
  "No comments yet.": "এখনও কোনো মন্তব্য নেই।",
  "Post a Comment": "মন্তব্য করুন",
  "Write a comment...": "মন্তব্য লিখুন...",
  "Post Comment": "মন্তব্য পোস্ট করুন",

  // Login / Register
  "Log In to Your Account": "আপনার অ্যাকাউন্টে লগইন করুন",
  "Create a Free Account": "একটি ফ্রি অ্যাকাউন্ট তৈরি করুন",
  "Sign In": "লগইন করুন",
  "Username": "ইউজারনেম",
  "Password": "পাসওয়ার্ড",
  "Forgot Password?": "পাসওয়ার্ড ভুলে গেছেন?",
  "Don't have an account?": "অ্যাকাউন্ট নেই?",
  "Already have an account?": "ইতিমধ্যে অ্যাকাউন্ট আছে?",
  "Register": "নিবন্ধন করুন",
  "Email Address": "ইমেইল ঠিকানা",
  "Search": "অনুসন্ধান",
  "Verify Facebook pages, check seller trust scores, and scan bKash/Nagad numbers before you pay.": "পেমেন্ট করার আগে ফেসবুক পেজ যাচাই করুন, বিক্রেতার ট্রাস্ট স্কোর চেক করুন এবং বিকাশ/নগদ নম্বর স্ক্যান করুন।",
  "Currently no threat entries indexed.": "বর্তমানে কোনো হুমকি এন্ট্রি ইনডেক্স করা নেই।",
  "Currently no public reviews registered.": "বর্তমানে কোনো পাবলিক রিভিউ নিবন্ধিত নেই।",
  "Anonymous User": "বেনামী ব্যবহারকারী",
  "Verified User": "যাচাইকৃত ব্যবহারকারী",
  "Recently": "সম্প্রতি",
  "Together, we can make Facebook a safer place to buy and sell.": "সবাই মিলে ফেসবুককে কেনাকাটার জন্য একটি নিরাপদ স্থান করে তুলি।",
  "Your reviews help protect others. Share your experiences with other online buyers.": "আপনার রিভিউ অন্যদের সুরক্ষিত করতে সাহায্য করে। অন্য অনলাইন ক্রেতাদের সাথে আপনার অভিজ্ঞতা শেয়ার করুন।",
  "HOW IT WORKS": "যেভাবে কাজ করে",
  "4 simple steps to shop with confidence": "নিরাপদে কেনাকাটার ৪টি সহজ ধাপ",
  "FB Page Review helps you research any Facebook page or seller using real community feedback and trust signals.": "ফেসবুক পেজ রিভিউ আপনাকে কমিউনিটির মতামত এবং ট্রাস্ট সিগন্যাল ব্যবহার করে যেকোনো পেজ বা বিক্রেতা সম্পর্কে জানতে সাহায্য করে।",
  "Search seller/page": "বিক্রেতা/পেজ অনুসন্ধান",
  "Look up a Facebook page or bKash number to pull up reports and ratings.": "রিপোর্ট এবং রেটিং দেখতে যেকোনো ফেসবুক পেজ বা বিকাশ নম্বর লিখে খুঁজুন।",
  "Review community feedback": "কমিউনিটির মতামত দেখুন",
  "Read reviews, verified transaction dates, scam tags, and buyer experiences.": "গ্রাহকের রিভিউ, লেনদেনের তারিখ, স্ক্যাম ট্যাগ এবং ক্রেতাদের অভিজ্ঞতা পড়ুন।",
  "Check seller ratings and fraud warnings": "বিক্রেতার রেটিং ও ঝুঁকি সতর্কতা চেক করুন",
  "See customer reviews, verification badges, and automated risk alerts.": "গ্রাহক রিভিউ, ভেরিফিকেশন ব্যাজ এবং স্বয়ংক্রিয় ঝুঁকি সতর্কতাগুলো দেখুন।",
  "Act safely": "নিরাপদে থাকুন",
  "Make informed decisions, avoid risky pages, and shop with peace of mind.": "জেনে-বুঝে সিদ্ধান্ত নিন, ঝুঁকিপূর্ণ পেজ এড়ান এবং নিশ্চিন্তে কেনাকাটা করুন।",
  "Stronger together, safer marketplace.": "একত্রে সবাই সুরক্ষিত, নিরাপদ কেনাকাটা।",
  "Real reviews from real buyers help everyone make smarter, safer choices.": "প্রদত্ত রিভিউ সবাইকে সঠিক এবং নিরাপদ সিদ্ধান্ত নিতে সাহায্য করে।",
  "Community Powered": "কমিউনিটি চালিত",
  "Transparent & Reliable": "স্বচ্ছ ও নির্ভরযোগ্য",
  "Privacy Focused": "প্রাইভেসি কেন্দ্রিক",
  "Search Facebook Page, brand, or category...": "ফেসবুক পেজ, ব্র্যান্ড বা ক্যাটাগরি খুঁজুন...",
  "All filters": "সব ফিল্টার",
  "Rating": "রেটিং",
  "Facebook Pages": "ফেসবুক পেজ",
  "Contact Number": "যোগাযোগের নম্বর",
  "Fraud Reports": "প্রতারণা রিপোর্ট",
  "Reported": "রিপোর্ট করা হয়েছে",
  "Previous": "পূর্ববর্তী",
  "Next page": "পরবর্তী পাতা",
  "No Facebook Pages found": "কোনো ফেসবুক পেজ পাওয়া যায়নি",
  "We couldn't find any Facebook Pages matching your search. Try checking your spelling or using different keywords.": "আমরা আপনার অনুসন্ধানের সাথে মিল থাকা কোনো ফেসবুক পেজ খুঁজে পাইনি। দয়া করে বানান চেক করুন অথবা অন্য কীওয়ার্ড ব্যবহার করুন।",
  "Can't find a Facebook Page?": "ফেসবুক পেজ খুঁজে পাচ্ছেন না?",
  "It might not be listed on FB Page Review yet. Add it and be the first to write a review.": "এটি হয়তো এখনো ফেসবুক পেজ রিভিউতে তালিকাভুক্ত হয়নি। এটি যুক্ত করুন এবং প্রথম রিভিউটি লিখুন।",
  "Add Facebook Page": "ফেসবুক পেজ যুক্ত করুন",
  "Facebook Page status": "ফেসবুক পেজের স্ট্যাটাস",
  "Facebook Pages that have been verified.": "যেসব ফেসবুক পেজ যাচাই বা ভেরিফাই করা হয়েছে।",
  "Number of reviews": "রিভিউর সংখ্যা",
  "Reset": "রিসেট",
  "Show Results": "ফলাফল দেখুন",
  "All": "সব",
  "Any": "যেকোনো",
  "Filters": "ফিল্টার",
  "Search Page": "পেজ খুঁজুন",
  "Search page name": "পেজের নাম লিখে খুঁজুন",
  "Listed Date": "তালিকাভুক্তির তারিখ",
  "All Dates": "সব তারিখ",
  "Today Only": "শুধু আজ",
  "This Week": "এই সপ্তাহ",
  "This Month": "এই মাস",
  "Page Size": "পেজের আকার",
  "10 per page": "প্রতি পাতায় ১০টি",
  "20 per page": "প্রতি পাতায় ২০টি",
  "50 per page": "প্রতি পাতায় ৫০টি",
  "100 per page": "প্রতি পাতায় ১০০টি",
  "Only verified billing numbers (bKash/Nagad/Phone)": "শুধুমাত্র যাচাইকৃত পেমেন্ট নম্বর (বিকাশ/নগদ/ফোন)",
  "Reset Filters": "ফিল্টার রিসেট করুন",
  "Detected Fraud Pages": "শনাক্তকৃত প্রতারক পেজ",
  "Review and monitor Facebook pages that have been flagged for fraudulent activity.": "প্রতারণামূলক কার্যকলাপের জন্য চিহ্নিত ফেসবুক পেজগুলো পর্যালোচনা ও মনিটর করুন।",
  "Total Flagged": "মোট চিহ্নিত",
  "Sort: Newest": "সাজান: নতুন আগে",
  "Sort: Oldest": "সাজান: পুরোনো আগে",
  "Sort: Reports": "সাজান: বেশি রিপোর্ট",
  "Sort: A-Z": "সাজান: ক-খ",
  "Filter Options": "ফিল্টার অপশন",
  "Close": "বন্ধ করুন",
  "Reset All Options": "সব অপশন রিসেট করুন",
  "Retrieving blacklisted page directory...": "কালো তালিকাভুক্ত পেজ ডিরেক্টরি লোড হচ্ছে...",
  "No records found": "কোনো রেকর্ড পাওয়া যায়নি",
  "No fraud profiles matched your current search and select inputs. Try clicking Reset Filters above.": "আপনার অনুসন্ধানের সাথে মেলে এমন কোনো প্রতারক প্রোফাইল পাওয়া যায়নি। উপরে ফিল্টার রিসেট করার চেষ্টা করুন।",
  "Showing": "দেখানো হচ্ছে",
  "of": "এর মধ্যে",
  "blacklisted pages": "কালো তালিকাভুক্ত পেজ",
  "Sort By:": "সাজান:",
  "Newest Listed": "নতুন তালিকাভুক্ত",
  "Oldest Listed": "পুরোনো তালিকাভুক্ত",
  "Most Reports": "সর্বাধিক রিপোর্ট",
  "A-Z Alphabetical": "বর্ণানুক্রমিকভাবে",
  "SL": "ক্রমিক",
  "Page": "পেজ",
  "N/A": "প্রযোজ্য নয়",
  "to": "থেকে",
  "entries": "টি এন্ট্রি",
  "Fraud Database": "প্রতারণা ডাটাবেজ",
  "A comprehensive list of reported Facebook pages and contact numbers associated with fraudulent activities.": "প্রতারণামূলক কার্যকলাপের সাথে জড়িত ফেসবুক পেজ এবং যোগাযোগ নম্বরের একটি বিস্তৃত তালিকা।",
  "Fraud Pages": "প্রতারক পেজ",
  "Fraud Numbers": "প্রতারক নম্বর",
  "Search page name...": "পেজের নাম লিখুন...",
  "Search number...": "নম্বর লিখুন...",
  "Most Reported": "সবচেয়ে বেশি রিপোর্ট",
  "Recently Updated": "সম্প্রতি আপডেট করা",
  "Oldest First": "পুরোনো আগে",
  "Most Linked Pages": "সবচেয়ে বেশি সংযুক্ত পেজ",
  "#": "ক্রমিক",
  "Page Details": "পেজের বিবরণ",
  "Primary Contact": "প্রধান যোগাযোগ",
  "Reports": "টি রিপোর্ট",
  "Actions": "অ্যাকশন",
  "Contact Number": "যোগাযোগ নম্বর",
  "Linked Pages": "সংযুক্ত পেজ",
  "Loading data...": "ডাটা লোড হচ্ছে...",
  "No matching records found.": "কোনো মিল পাওয়া যায়নি।",
  "Facebook Link": "ফেসবুক লিঙ্ক",
  "Unknown": "অজানা",
  "Updated": "আপডেট করা হয়েছে",
  "View Details": "বিস্তারিত দেখুন",
  "Reported": "রিপোর্টকৃত",
  "Suspicious": "সন্দেহজনক",
  "linked pages": "টি সংযুক্ত পেজ",
  "Unnamed Page": "নামহীন পেজ",
  "Since": "থেকে",
  "Report again": "আবার রিপোর্ট করুন",
  "First Page": "প্রথম পাতা",
  "Previous Page": "আগের পাতা",
  "Next Page": "পরের পাতা",
  "Last Page": "শেষ পাতা",
  "Contact": "যোগাযোগ",
  "Number": "নম্বর",
  "Excellent": "চমৎকার",
  "Great": "দারুণ",
  "Average": "মোটামুটি",
  "Poor": "খারাপ",
  "No reviews": "কোনো পর্যালোচনা নেই",
  "Claimed Business": "দাবীকৃত ব্যবসা",
  "Unclaimed Profile": "অদাবীকৃত প্রোফাইল",
  "Fraud": "প্রতারক",
  "💀 Old/Dead Page": "💀 পুরোনো/নিষ্ক্রিয় পেজ",
  "⭐ Verified Seller": "⭐ যাচাইকৃত বিক্রেতা",
  "🔍 Under Review": "🔍 পর্যালোচনার অধীনে",
  "⚠️ Suspicious": "⚠️ সন্দেহজনক",
  "🏆 Gold Seller": "🏆 গোল্ড বিক্রেতা",
  "reviews": "টি পর্যালোচনা",
  "Fraud Reports": "টি প্রতারণার রিপোর্ট",
  "Edit Review": "পর্যালোচনা সম্পাদন",
  "Write Review": "পর্যালোচনা লিখুন",
  "Report Fraud": "প্রতারণার রিপোর্ট",
  "Visit Facebook Page": "ফেসবুক পেজ ভিজিট করুন",
  "Warning: Reported as Fraud": "সতর্কতা: প্রতারক হিসেবে রিপোর্ট করা হয়েছে",
  "This page has been reported as fraud. Do not send any money, advanced payments, or personal details to this seller.": "এই পেজটিকে প্রতারক হিসেবে রিপোর্ট করা হয়েছে। এই বিক্রেতাকে কোনো টাকা, অগ্রিম অর্থ বা ব্যক্তিগত বিবরণ পাঠাবেন না।",
  "Warning: Active Disputes": "সতর্কতা: সক্রিয় বিতর্ক",
  "Users have reported fraud complaints against this page. Please scroll down to check all evidence and reviews before making any purchases.": "ব্যবহারকারীরা এই পেজের বিরুদ্ধে প্রতারণার অভিযোগ করেছেন। কোনো কেনাকাটা করার আগে অনুগ্রহ করে নিচে স্ক্রোল করে সমস্ত প্রমাণ এবং পর্যালোচনা দেখে নিন।",
  "Summary": "সারসংক্ষেপ",
  "About Pages": "পেজ পরিচিতি",
  "Reviews": "পর্যালোচনা",
  "Facebook Page Details": "ফেসবুক পেজের বিবরণ",
  "No specific page description provided by the business yet. This shop has not customized their public registration info.": "ব্যবসা প্রতিষ্ঠান দ্বারা এখনও কোনো সুনির্দিষ্ট পেজের বিবরণ প্রদান করা হয়নি। এই শপটি তাদের জনসাধারণের নিবন্ধনের তথ্য কাস্টমাইজ করেনি।",
  "Verified Contact Directory": "যাচাইকৃত যোগাযোগ ডিরেক্টরি",
  "Mobile Contact": "মোবাইল যোগাযোগ",
  "External Link": "বহিরাগত লিঙ্ক",
  "Facebook Page": "ফেসবুক পেজ",
  "Supported Payment Modes": "সমর্থিত পেমেন্ট পদ্ধতি",
  "payment accounts flagged in reviews": "পর্যালোচনায় চিহ্নিত পেমেন্ট অ্যাকাউন্টসমূহ",
  "Other consumers noted these money transfers or wallet accounts in active scam reports:": "অন্যান্য ভোক্তারা সক্রিয় স্ক্যাম রিপোর্টে এই অর্থ স্থানান্তর বা ওয়ালেট অ্যাকাউন্টগুলো উল্লেখ করেছেন:",
  "Merchant Reviews": "বিক্রেতার পর্যালোচনা",
  "reviews verified, filtered results are listed below": "টি পর্যালোচনা যাচাই করা হয়েছে, ফিল্টার করা ফলাফল নিচে তালিকাভুক্ত করা হলো",
  "Write a review": "একটি পর্যালোচনা লিখুন",
  "Search reviews by keyword...": "কীওয়ার্ড দ্বারা পর্যালোচনা খুঁজুন...",
  "Filter": "ফিল্টার",
  "Most Recent": "সাম্প্রতিক",
  "Oldest": "পুরোনো",
  "Loading business profile...": "ব্যবসায়িক প্রোফাইল লোড হচ্ছে...",
  "Business Page Not Found": "ব্যবসায়িক পেজটি পাওয়া যায়নি",
  "We couldn't retrieve information for the requested profile.": "আমরা অনুরোধ করা প্রোফাইলের জন্য তথ্য পুনরুদ্ধার করতে পারিনি।",
  "Return Home": "হোমে ফিরে যান",
  "No matching reviews found": "কোনো মানানসই পর্যালোচনা পাওয়া যায়নি",
  "Try adjusting your filters, searching another keyword, or resetting results.": "আপনার ফিল্টার পরিবর্তন করুন, অন্য কীওয়ার্ড দিয়ে খুঁজুন, বা ফলাফল রিসেট করুন।",
  "Registered Buyer": "নিবন্ধিত ক্রেতা",
  "Verified Guest": "যাচাইকৃত অতিথি",
  "Verified Buyer": "যাচাইকৃত ক্রেতা",
  "See Less": "কম দেখুন",
  "See More": "আরো দেখুন",
  "Useful": "উপকারী",
  "Share": "শেয়ার",
  "Copied!": "কপি হয়েছে!",
  "Link Copied!": "লিঙ্ক কপি করা হয়েছে!",
  "Edit": "সম্পাদন করুন",
  "CONFIRM DELETE": "মুছে ফেলার নিশ্চিতকরণ",
  "Delete": "মুছে ফেলুন",
  "Report Review": "রিপোর্ট করুন",
  "Dispute Rating": "রেটিং বিতর্ক",
  "File an official merchant dispute. Admins will review the dispute reasons and page verification credentials.": "একটি অফিসিয়াল বিক্রেতা বিতর্ক দায়ের করুন। এডমিনরা বিতর্কের কারণ এবং পেজের যাচাইকরণের প্রমাণাদি পর্যালোচনা করবেন।",
  "Spam or Fake": "স্প্যাম বা ফেক",
  "Hate Speech": "বিদ্বেষমূলক বক্তব্য",
  "Harassment": "হয়রানি",
  "Profanity": "অশালীন ভাষা",
  "Not a real customer": "আসল গ্রাহক নয়",
  "State your detailed argument or provide transaction evidence link...": "আপনার বিস্তারিত যুক্তি লিখুন বা লেনদেনের প্রমাণের লিঙ্ক দিন...",
  "Submitting...": "জমা দেওয়া হচ্ছে...",
  "Submit Dispute": "বিতর্ক জমা দিন",
  "Response from": "থেকে উত্তর",
  "Reply as Owner": "মালিক হিসেবে উত্তর দিন",
  "Publish Shop response": "শপের প্রতিক্রিয়া প্রকাশ করুন",
  "Write a polite and professional response...": "একটি ভদ্র এবং পেশাদার প্রতিক্রিয়া লিখুন...",
  "Posting...": "পোস্ট করা হচ্ছে...",
  "Post Reply": "উত্তর পোস্ট করুন",
  "Merchant Summary": "বিক্রেতার সারসংক্ষেপ",
  "out of 5.0": "৫.০ এর মধ্যে",
  "Based on": "ভিত্তি করে",
  "ratings": "টি রেটিং এর উপর",
  "star": "স্টার",
  "Refine Reviews": "পর্যালোচনা পরিমার্জন করুন",
  "Filter by Rating": "রেটিং দ্বারা ফিল্টার করুন",
  "Assurance Metrics": "নিশ্চয়তা সূচক",
  "Verified Buyer Review": "যাচাইকৃত ক্রেতার পর্যালোচনা",
  "Only lists reviews with verified purchase confirmation.": "শুধুমাত্র যাচাইকৃত ক্রয়ের নিশ্চিতকরণসহ পর্যালোচনাগুলো দেখাবে।",
  "Contains Shop Replies": "শপের উত্তর রয়েছে",
  "Only displays reviews with answers from the seller profile.": "শুধুমাত্র বিক্রেতার প্রোফাইল থেকে উত্তরসহ পর্যালোচনাগুলো দেখাবে।",
  "Date of Submission": "জমা দেওয়ার তারিখ",
  "All history": "সব ইতিহাস",
  "Last 30 days": "গত ৩০ দিন",
  "Last 3 months": "গত ৩ মাস",
  "Last 6 months": "গত ৬ মাস",
  "Last 12 months": "গত ১২ মাস",
  "default": "ডিফল্ট",
  "Reset All": "সব রিসেট করুন",
  "Updating list...": "তালিকা আপডেট হচ্ছে...",
  "Display": "প্রদর্শন করুন",
  "Results": "টি ফলাফল",
  "Tap arrows or swipe to navigate": "ন্যাভিগেট করতে তীর চিহ্নে আলতো চাপুন বা সোয়াইপ করুন",
  "Click anywhere outside to close": "বন্ধ করতে বাইরে যেকোনো স্থানে ক্লিক করুন"
};

const banglaDigits = ['০', '১', '২', '৩', '৪', '৫', '৬', '৭', '৮', '৯'];

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved === 'en' || saved === 'bn') ? saved : 'bn';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    if (language === 'en') return key;
    return translations[key] || key;
  };

  const n = (num: number | string): string => {
    const str = String(num);
    if (language === 'en') return str;
    return str.replace(/[0-9]/g, (w) => banglaDigits[parseInt(w, 10)]);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, n }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
